# Config file for automatic testing at travis-ci.com

stages:
  - test
  - name: deploy
    if:  type = pull_request OR branch = master OR tag IS present AND repo = scotthavens/pysnobal

# defining the unittest jobs
unittest: &unittest
  stage: test
  os: linux
  dist: bionic
  language: python
  cache: pip
  install: 
    - python3 --version
    - python3 -m pip install tox-travis
  script: tox

jobs:
  include:
    # test stage
    - <<: *unittest
      python: 3.6
      env: TOXENV=py36

    - <<: *unittest
      python: 3.6
      env: TOXENV=coverage

    - <<: *unittest
      python: 3.6
      env: TOXENV=flake8

    - <<: *unittest
      python: 3.7
      env: TOXENV=py37

    - <<: *unittest
      python: 3.8
      env: TOXENV=py38

    - <<: *unittest
      os: osx
      osx_image: xcode11.2  # Python 3.7.X running on macOS 10.14
      language: shell
      env:
        - TOXENV=py37
        - NOT_ON_GOLD_HOST=yup

  allow_failures:
    - python: 3.6
      env: TOXENV=flake8

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  cleanup: true
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  user: __token__
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: scotthavens/pysnobal
